#!/bin/sh

# Get the pwd of this script.
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check if scripts symlink already exists. Running this when it does results in oddness.
# "Teh oddness" is 'scripts' inside /usr/local/scripts pointing the original location of
# /usr/local/scripts. So linking inside itself in the original directory, obviously because
# it is a symlink.
[ ! -e /usr/local/scripts ] && ln -s $DIR /usr/local/scripts

# Call the script that makes symlinks.
$DIR/makelinks.sh
