#!/usr/bin/env bash

setup () {
    if [ -L "$BASH_SOURCE" ]; then
        SCRIPTS_DIR=$(dirname $(readlink $BASH_SOURCE))
    else
        SCRIPTS_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    fi

    if [ $# -gt 0 ]; then
        tagname=$1
    else
        tagname=$(basename $PWD)
    fi

    echo "Initialising git scripts for $tagname"

    if [ -d .git >/dev/null 2>&1 ]; then
        LOCAL_SCRIPTS_DIR=.scripts
        mkdir $LOCAL_SCRIPTS_DIR
        ln -sv $SCRIPTS_DIR/scripts $LOCAL_SCRIPTS_DIR/todos
        cp $SCRIPTS_DIR/dotenv-file .env
        echo "export TODO_AREA=$tagname" >> .env
        TODO_AREA=$tagname $LOCAL_SCRIPTS_DIR/todos/create-area
        TODO_AREA=$tagname $LOCAL_SCRIPTS_DIR/todos/get-todos
    else
        if git rev-parse --git-dir > /dev/null 2>&1; then
            echo "Must install at root of git repo"
        else
            echo "Not a git repo"
        fi
    fi
}

setup

# Trigger autoenv
cd .
